#!/bin/bash

# Initialize variables with default values
CONFIG_DIRECTORY=/etc/db-backup
HELP_FLAG=0

# Define function to print out help message
print_help() {
    cat <<EOF
Usage: $0 [options] <config_name>

Creates a backup of all databases specified in the configuration file.

Positional arguments:
  config_name          Name of the configuration to use. If not specified, all files in the configurations directory with the .cfg extension will be used.

Options:
  -c, --config-dir         The path to directory containing configurations. (default: $CONFIG_DIRECTORY)
  -r, --retention POLICY   Retention policy type. Possible values: daily, weekly, monthly, yearly. If set, the value will be used as a suffix in the subdirectory name.
  -m, --send-mail          Send an email notification after the backup is complete.
                           If this flag is set, make sure to set the email address in the configuration file.
  -h, --help               Print this help message and exit.

The configuration files are shell scripts that define the following variables:
  - DB_NAMES        An array of database names to backup
  - DB_HOST         The hostname or IP address of the database server
  - DB_PORT         The port number of the database server
  - DB_USER         The username to use when connecting to the database server
  - DB_PASSWORD     The password to use when connecting to the database server
  - BACKUP_DIR      The directory where the backups will be stored

Examples:
  $0                  # Creates a backup using all the configuration files.
  $0 mydb             # Creates a backup using the specified configuration file "mydb.cfg".
  $0 -r daily         # Creates a backup using all the configuration files and use a "daily" retention policy.
  $0 -r weekly -m mydb   # Creates a backup using the specified configuration file "mydb.cfg" and use a "weekly" retention policy, and send an email notification after the backup is complete.
  $0 -h               # Prints this help message.
EOF
}

LOG_FILE="/tmp/db-backup-$RANDOM.log"
echo "Writing into the log file: $LOG_FILE"

# Define a function to be called at the end of the script
function cleanup {
  echo "Cleaning up..."
  rm -f $LOG_FILE
}

# Register the cleanup function to be called on script exit
trap cleanup EXIT

function write {
  echo -e "$1"

  no_color=$(echo -e "$1" | awk '{gsub(/\033\[[0-9;]*m/,"")}1')
  if [[ $1 == *"\c" ]]; then
    echo -ne "$no_color" >> $LOG_FILE
  else
    echo -e "$no_color" >> $LOG_FILE
  fi
}

function log {
  cas=$(date +"%H:%M:%S")
  write "[$cas] $1"
}

# Loop through options and assign values
while [[ "$#" -gt 0 ]]; do
  case $1 in
    -c|--config-dir)
        CONFIG_DIRECTORY="$2"
        shift
        ;;
    -r|--retention)
        RETENTION_POLICY="$2"
        shift
        ;;
    -m|--send-mail)
        SEND_MAIL=true
        shift
        ;;
    -h|--help)
        HELP_FLAG=1
        ;;
    -*)
        # If unknown option or argument is given, print help message and exit
        print_help
        exit 1
        ;;
  esac
  shift
done

# If help flag is set, print help message and exit
if [ $HELP_FLAG -eq 1 ]; then
    print_help
    exit 0
fi

# Get the config file(s) to use
if [ $# -eq 0 ]; then
    CONFIG_FILES="$CONFIG_DIRECTORY/*.cfg"
else
    CONFIG_FILES="$CONFIG_DIRECTORY/$1.cfg"
fi

# Validate retention policy option
if [[ -v RETENTION_POLICY ]] && \
   ! [[ $RETENTION_POLICY =~ ^(daily|weekly|monthly|yearly)$ ]]; then
    echo "Error: Invalid retention policy option. Valid options are 'daily', 'weekly', 'monthly', or 'yearly'." >&2
    exit 1
fi

# Loop through each config file
# shellcheck disable=SC2068
for CONFIG_FILE in ${CONFIG_FILES[@]}; do

    BACKUP_NAME=$(basename "$CONFIG_FILE" | cut -d'.' -f1)

    # Check if the config file exists
    if [ ! -f "$CONFIG_FILE" ]; then
        echo "Error: Config file $CONFIG_FILE not found." >&2
        exit 1
    fi

    echo -e "\nProcessing config file: $CONFIG_FILE"

    # Read config file
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"

    # Check if the backup destination directory exists
    if [ ! -d "$BACKUP_DIR" ]; then
        echo "Error: Backup destination directory $BACKUP_DIR not found." >&2
        exit 1
    fi

    touch $LOG_FILE

    DATE_TIME=$(date +"%Y-%m-%d_%H%M%S")
    if [ -n "$RETENTION_POLICY" ]; then
        BACKUP_SUBDIR="${BACKUP_NAME}_${DATE_TIME}_${RETENTION_POLICY}"
    else
        BACKUP_SUBDIR="${BACKUP_NAME}_${DATE_TIME}"
    fi
    BACKUP_SUBDIR_FULL="$BACKUP_DIR/$BACKUP_SUBDIR"

    clear

    write "***************************************"
    write "DATABASE BACKUP CREATION"
    write "***************************************"
    write "Date         : $(date +'%F %X')"
    write "Backup name  : $BACKUP_NAME"
    write "Database     : $DB_HOST:$DB_PORT"
    write "Backup dir   : $BACKUP_SUBDIR_FULL"
    write " "
    write "E-mail (from): $EMAILFROM"
    write "E-mail (to)  : $EMAILTO"
    write "***************************************"
    write ""

    # Create backup subdirectory
    mkdir -p "$BACKUP_SUBDIR_FULL"

    # Initialize the array to store failed backups' information
    FAILED_BACKUPS=()

    # Backup each database
    for DB in "${DB_NAMES[@]}"; do
        # Create backup file name
        FILENAME="$DB.$DATE_TIME.sql.gz"
        BACKUP_FILE="$BACKUP_SUBDIR_FULL/$FILENAME"

        # Print backup start message
        log "Database: $DB ... \c"

        # Run mysqldump to create backup
        mysqldump \
          -h "$DB_HOST" \
          -P "$DB_PORT" \
          -u "$DB_USER" \
          -p"$DB_PASSWORD" \
          --single-transaction \
          --routines \
          --triggers \
          --events "$DB" \
          | gzip > "$BACKUP_FILE"


        # Print backup end message
        if [[ ${PIPESTATUS[0]} -eq 0 ]]; then
            write "\033[32mdone\033[0m"
        else
            # Add failed backup's information to the array
            FAILED_BACKUPS+=("$BACKUP_NAME.$DB")

            write "\033[31mfailed\033[0m"
        fi

    done

    # Print completion message
    write "\nBackups of $BACKUP_NAME completed to: $BACKUP_SUBDIR_FULL"

    # size data
    write "Backup size: \c"
    SIZE=$(du -hs "$BACKUP_SUBDIR_FULL" | awk '{print $1}')
    write "$SIZE"

    cp "$LOG_FILE" "$BACKUP_SUBDIR_FULL/db-backup.log"

done

# Print out the number of failed backups and their information (if any)
if [ ${#FAILED_BACKUPS[@]} -eq 0 ]; then
    write "\nAll database backups completed successfully."
else
    write "\n${#FAILED_BACKUPS[@]} backups failed:"
    OUTCOME="FAILED"
    for failed_backup in "${FAILED_BACKUPS[@]}"; do
        write "$failed_backup"
    done
fi

# sending mail
SUMMARY="[db-backup] $BACKUP_NAME ($SIZE) $OUTCOME"
if [[ "$SEND_MAIL" == true ]]; then
  # sending mail
  cat $LOG_FILE | mail -s "$SUMMARY" -a "From: $EMAILFROM" $EMAILTO

fi